export const GET_TODOS_LOADING ="GET_TODOS_LOADING"
export const GET_TODOS_SUCESS ="GET_TODOS_SUCESS"
export const GET_TODOS_FAILURE ="GET_TODOS_FAILURE"
export const POST_TODOS_LOADING ="POST_TODOS_LOADING"
export const POST_TODOS_SUCESS ="POST_TODOS_SUCESS"
export const POST_TODOS_FAILURE ="POST_TODOS_FAILURE";